/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package encryptedmessageapp;

/**
 *
 * @author seang
 */
import java.io.*;
import java.net.*;
import java.security.*;
import java.security.spec.*;
import java.util.Base64;
import javax.crypto.*;
import javax.crypto.spec.*;

public class Client {

    // The server’s address (localhost = same computer)
    private static final String HOST = "localhost";

    // Must match the port used by the server
    private static final int PORT = 12345;

    // The server's RSA public key (received during handshake)
    private PublicKey serverPublicKey;

    // AES session key (generated by client, shared with server)
    private SecretKey aesKey;

    // Main entry point
    public static void main(String[] args) {
        try {
            // Create a new instance of the client and start it
            new Client().start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Method to start the client
    public void start() throws Exception {

        //Connect to the server via TCP socket
        Socket socket = new Socket(HOST, PORT);
        System.out.println("Connected to server " + HOST + ":" + PORT);

        // Create input/output streams for communication
        BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));   // For reading messages
        PrintWriter out = new PrintWriter(socket.getOutputStream(), true);                        // For sending messages
        BufferedReader console = new BufferedReader(new InputStreamReader(System.in));            // For reading user input

        // --- HANDSHAKE PHASE ---
        // This part securely shares an AES key between client and server.

        // Step 1: Receive server's RSA public key (Base64 encoded)
        String serverPubBase64 = in.readLine();  // Server sends its public key as Base64 text
        if (serverPubBase64 == null) {
            throw new IOException("Server closed before sending public key.");
        }

        // Step 2: Decode Base64 into raw bytes
        byte[] serverPubBytes = Base64.getDecoder().decode(serverPubBase64);

        // Step 3: Convert the bytes into a real PublicKey object (X.509 format)
        serverPublicKey = KeyFactory.getInstance("RSA").generatePublic(new X509EncodedKeySpec(serverPubBytes));
        System.out.println("Received server RSA public key.");

        // Step 4: Generate a new AES session key (for encrypting all chat messages)
        aesKey = generateAESKey();

        // Step 5: Encrypt AES key using the server’s RSA public key (so only server can decrypt it)
        byte[] encryptedAesKey = rsaEncrypt(aesKey.getEncoded(), serverPublicKey);

        // Step 6: Send the encrypted AES key (as Base64 text) to the server
        out.println(Base64.getEncoder().encodeToString(encryptedAesKey));
        System.out.println("Sent AES session key to server (RSA-encrypted). Chat ready!");

        // --- MESSAGE EXCHANGE PHASE ---
        // After handshake, both sides share the same AES key.

        // Thread for continuously receiving and decrypting messages from server
        Thread reader = new Thread(() -> {
            try {
                String line;
                while ((line = in.readLine()) != null) {
                    // Each line from server is formatted as IV_BASE64:CIPHERTEXT_BASE64
                    String[] parts = line.split(":");

                    // Validate message format
                    if (parts.length != 2) {
                        System.out.println("Malformed message received.");
                        continue;
                    }

                    // Decode Base64 strings back into bytes
                    byte[] iv = Base64.getDecoder().decode(parts[0]);
                    byte[] cipherBytes = Base64.getDecoder().decode(parts[1]);

                    // Decrypt using AES-GCM
                    String plaintext = aesGcmDecrypt(aesKey, iv, cipherBytes);

                    // If server says "bye", end session
                    if (plaintext.equalsIgnoreCase("bye")) {
                        System.out.println("Server ended the chat.");
                        break;
                    }

                    // Display decrypted message
                    System.out.println("Server: " + plaintext);
                }
            } catch (Exception e) {
                System.out.println("Reader error: " + e.getMessage());
            }
        });

        // Start the reader thread
        reader.start();

        // Main thread: read user input and send encrypted messages
        try {
            String message;
            while ((message = console.readLine()) != null) {

                // If user types "bye", send and close
                if (message.equalsIgnoreCase("bye")) {
                    sendEncrypted(out, aesKey, message);
                    break;
                }

                // Encrypt and send normal messages
                sendEncrypted(out, aesKey, message);
            }
        } finally {
            // Clean up network connection
            socket.close();
            System.out.println("Client closed.");
        }
    }

    // Helper method to encrypt and send messages using AES-GCM
    private static void sendEncrypted(PrintWriter out, SecretKey aesKey, String plaintext) throws Exception {
        // Generate a unique 12-byte random IV for each message
        byte[] iv = new byte[12];
        SecureRandom random = new SecureRandom();
        random.nextBytes(iv);

        // Encrypt the plaintext
        byte[] cipherBytes = aesGcmEncrypt(aesKey, iv, plaintext);

        // Send Base64(iv):Base64(ciphertext)
        String outLine = Base64.getEncoder().encodeToString(iv) + ":" +
                         Base64.getEncoder().encodeToString(cipherBytes);
        out.println(outLine);
    }

    // --- RSA UTILITIES ---

    // Encrypt data using RSA public key (OAEP padding for modern security)
    private static byte[] rsaEncrypt(byte[] data, PublicKey publicKey) throws Exception {
        Cipher rsa = Cipher.getInstance("RSA/ECB/OAEPWithSHA-256AndMGF1Padding");
        rsa.init(Cipher.ENCRYPT_MODE, publicKey);
        return rsa.doFinal(data);
    }

    // --- AES UTILITIES ---

    // Generate a fresh 128-bit AES key
    private static SecretKey generateAESKey() throws Exception {
        KeyGenerator kg = KeyGenerator.getInstance("AES");
        kg.init(128);  // 128-bit key size
        return kg.generateKey();
    }

    // Encrypt plaintext with AES-GCM
    private static byte[] aesGcmEncrypt(SecretKey key, byte[] iv, String plaintext) throws Exception {
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        GCMParameterSpec spec = new GCMParameterSpec(128, iv); // 128-bit auth tag
        cipher.init(Cipher.ENCRYPT_MODE, key, spec);
        return cipher.doFinal(plaintext.getBytes("UTF-8"));
    }

    // Decrypt ciphertext with AES-GCM
    private static String aesGcmDecrypt(SecretKey key, byte[] iv, byte[] ciphertext) throws Exception {
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        GCMParameterSpec spec = new GCMParameterSpec(128, iv);
        cipher.init(Cipher.DECRYPT_MODE, key, spec);
        byte[] plain = cipher.doFinal(ciphertext);
        return new String(plain, "UTF-8");
    }
}

